services:
  broker:
    build: broker/
    ports:
      - "8885:8885"
    networks:
      - facility

  server:
    build: server/
    env_file:
      - ./server/.env
    depends_on:
      - broker
    networks:
      - facility

  sddb:
    build: database/
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database

networks:
  facility:
  database:

volumes:
  pgdata:
