# Integration test between broker, local server, and database
# Steps: `docker-compose build && docker-compose up`

services:
  ##################################
  # Independently started services #
  ##################################
  broker:
    build: broker/
    ports:
      - "8885:8885"
    networks:
      - broker

  sddb:
    build: database/
    command: postgres -c config_file=/etc/postgres.conf
    env_file:
      - ${PWD}/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - database

  ################################
  # Dependently started services #
  ################################
  proxy:
    build:
      context: ${PWD}/proxy
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - broker # will be redis
    networks:
      - facility

  batch-router:
    build: 
      context: ${PWD}/batch-router
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - proxy # will be redis
    networks:
      - facility

  client:
    build: 
      context: ${PWD}/client
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - batch-appp
    networks:
      - facility

  clock:
    build: 
      context: ${PWD}/clock
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - client
    networks:
      - facility

networks:
  broker:
  facility:
  database:

volumes: 
  db:
