# Integration test between broker, local server, and database

# Steps: 
# docker-compose build && docker-compose up 
# <new terminal> cd server/
# ./run.sh build/client
# <new terminal> docker-compose restart clock

services:
  broker:
    build: broker/
    ports:
      - "8885:8885"
    networks:
      - facility

  server:
    build: 
      context: ${PWD}/server
      dockerfile: Dockerfile
      target: server
    env_file:
      - ${PWD}/server/.env
    depends_on:
      - broker
    networks:
      - facility

  clock:
    build: 
      context: ${PWD}/server
      dockerfile: Dockerfile
      target: clock
    env_file:
      - ${PWD}/server/.env
    depends_on:
      - server
    networks:
      - facility

  sddb:
    build: database/
    command: postgres -c config_file=/etc/postgres.conf
    env_file:
      - ${PWD}/database/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - database

networks:
  facility:
  database:

volumes: 
  db:
