# Integration test between broker, local server, and database
# Steps: `docker-compose build && docker-compose up`
# Individual: `dc start service` and `dc stop service`

services:
  ##################################
  # Independently started services #
  ##################################
  broker:
    build: broker/
    ports:
      - "8885:8885"
    networks:
      - broker

  redis:
    build: redis/
    ports:
      - "6379:6379"
    volumes:
      - rdb:/rdb
    networks:
      - redis

  sddb:
    build: database/
    command: postgres -c config_file=/etc/postgres.conf
    env_file:
      - ${PWD}/.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - database

  ################################
  # Dependently started services #
  ################################
  api:
    build:
      context: ${PWD}/api
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    ports:
      - "3000:3000"
    depends_on:
      - sddb
    networks:
      - api

  clock:
    build: 
      context: ${PWD}/clock
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - client
      - batch-router
    networks:
      - facility

  client:
    build: 
      context: ${PWD}/client
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - broker
    networks:
      - facility

  batch-router:
    build: 
      context: ${PWD}/batch-router
      dockerfile: Dockerfile
      target: main
    env_file:
      - ${PWD}/.env
    depends_on:
      - broker
      - redis
      - sddb
    networks:
      - facility

networks:
  api:
  broker:
  database:
  facility:
  redis:

volumes: 
  db:
  rdb:
