// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api.proto
// Protobuf C++ Version: 5.27.0

#include "api.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace api {

inline constexpr SensorRows::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entry_id_{0},
        facility_id_{0},
        temp_{0},
        rh_{0},
        epoch_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SensorRows::SensorRows(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SensorRowsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SensorRowsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SensorRowsDefaultTypeInternal() {}
  union {
    SensorRows _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SensorRowsDefaultTypeInternal _SensorRows_default_instance_;
}  // namespace api
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_api_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_api_2eproto = nullptr;
const ::uint32_t
    TableStruct_api_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.entry_id_),
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.facility_id_),
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.device_),
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.temp_),
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.rh_),
        PROTOBUF_FIELD_OFFSET(::api::SensorRows, _impl_.epoch_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::api::SensorRows)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::api::_SensorRows_default_instance_._instance,
};
const char descriptor_table_protodef_api_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tapi.proto\022\003api\032\033google/protobuf/empty."
    "proto\"l\n\nSensorRows\022\020\n\010entry_id\030\001 \001(\005\022\023\n"
    "\013facility_id\030\002 \001(\005\022\016\n\006device\030\003 \001(\t\022\014\n\004te"
    "mp\030\004 \001(\005\022\n\n\002rh\030\005 \001(\002\022\r\n\005epoch\030\006 \001(\0032E\n\005Q"
    "uery\022<\n\rGetSensorRows\022\026.google.protobuf."
    "Empty\032\017.api.SensorRows\"\0000\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_api_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_api_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_api_2eproto = {
    false,
    false,
    234,
    descriptor_table_protodef_api_2eproto,
    "api.proto",
    &descriptor_table_api_2eproto_once,
    descriptor_table_api_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_api_2eproto::offsets,
    file_level_enum_descriptors_api_2eproto,
    file_level_service_descriptors_api_2eproto,
};
namespace api {
// ===================================================================

class SensorRows::_Internal {
 public:
};

SensorRows::SensorRows(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:api.SensorRows)
}
inline PROTOBUF_NDEBUG_INLINE SensorRows::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::api::SensorRows& from_msg)
      : device_(arena, from.device_),
        _cached_size_{0} {}

SensorRows::SensorRows(
    ::google::protobuf::Arena* arena,
    const SensorRows& from)
    : ::google::protobuf::Message(arena) {
  SensorRows* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, entry_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, entry_id_),
           offsetof(Impl_, epoch_) -
               offsetof(Impl_, entry_id_) +
               sizeof(Impl_::epoch_));

  // @@protoc_insertion_point(copy_constructor:api.SensorRows)
}
inline PROTOBUF_NDEBUG_INLINE SensorRows::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_(arena),
        _cached_size_{0} {}

inline void SensorRows::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, entry_id_),
           0,
           offsetof(Impl_, epoch_) -
               offsetof(Impl_, entry_id_) +
               sizeof(Impl_::epoch_));
}
SensorRows::~SensorRows() {
  // @@protoc_insertion_point(destructor:api.SensorRows)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SensorRows::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.device_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SensorRows::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SensorRows, _impl_._cached_size_),
              false,
          },
          &SensorRows::MergeImpl,
          &SensorRows::kDescriptorMethods,
          &descriptor_table_api_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 29, 2> SensorRows::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SensorRows_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::api::SensorRows>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 entry_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SensorRows, _impl_.entry_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.entry_id_)}},
    // int32 facility_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SensorRows, _impl_.facility_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.facility_id_)}},
    // string device = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.device_)}},
    // int32 temp = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SensorRows, _impl_.temp_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.temp_)}},
    // float rh = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.rh_)}},
    // int64 epoch = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SensorRows, _impl_.epoch_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.epoch_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 entry_id = 1;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.entry_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 facility_id = 2;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.facility_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string device = 3;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.device_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 temp = 4;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.temp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float rh = 5;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.rh_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // int64 epoch = 6;
    {PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.epoch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\16\0\0\6\0\0\0\0"
    "api.SensorRows"
    "device"
  }},
};

PROTOBUF_NOINLINE void SensorRows::Clear() {
// @@protoc_insertion_point(message_clear_start:api.SensorRows)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_.ClearToEmpty();
  ::memset(&_impl_.entry_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.epoch_) -
      reinterpret_cast<char*>(&_impl_.entry_id_)) + sizeof(_impl_.epoch_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SensorRows::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:api.SensorRows)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 entry_id = 1;
  if (this->_internal_entry_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_entry_id(), target);
  }

  // int32 facility_id = 2;
  if (this->_internal_facility_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_facility_id(), target);
  }

  // string device = 3;
  if (!this->_internal_device().empty()) {
    const std::string& _s = this->_internal_device();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "api.SensorRows.device");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // int32 temp = 4;
  if (this->_internal_temp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_temp(), target);
  }

  // float rh = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = this->_internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_rh(), target);
  }

  // int64 epoch = 6;
  if (this->_internal_epoch() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<6>(
            stream, this->_internal_epoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:api.SensorRows)
  return target;
}

::size_t SensorRows::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:api.SensorRows)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string device = 3;
  if (!this->_internal_device().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_device());
  }

  // int32 entry_id = 1;
  if (this->_internal_entry_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_entry_id());
  }

  // int32 facility_id = 2;
  if (this->_internal_facility_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_facility_id());
  }

  // int32 temp = 4;
  if (this->_internal_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_temp());
  }

  // float rh = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = this->_internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    total_size += 5;
  }

  // int64 epoch = 6;
  if (this->_internal_epoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_epoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SensorRows::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SensorRows*>(&to_msg);
  auto& from = static_cast<const SensorRows&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:api.SensorRows)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device().empty()) {
    _this->_internal_set_device(from._internal_device());
  }
  if (from._internal_entry_id() != 0) {
    _this->_impl_.entry_id_ = from._impl_.entry_id_;
  }
  if (from._internal_facility_id() != 0) {
    _this->_impl_.facility_id_ = from._impl_.facility_id_;
  }
  if (from._internal_temp() != 0) {
    _this->_impl_.temp_ = from._impl_.temp_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = from._internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    _this->_impl_.rh_ = from._impl_.rh_;
  }
  if (from._internal_epoch() != 0) {
    _this->_impl_.epoch_ = from._impl_.epoch_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SensorRows::CopyFrom(const SensorRows& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:api.SensorRows)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SensorRows::InternalSwap(SensorRows* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_, &other->_impl_.device_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.epoch_)
      + sizeof(SensorRows::_impl_.epoch_)
      - PROTOBUF_FIELD_OFFSET(SensorRows, _impl_.entry_id_)>(
          reinterpret_cast<char*>(&_impl_.entry_id_),
          reinterpret_cast<char*>(&other->_impl_.entry_id_));
}

::google::protobuf::Metadata SensorRows::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace api
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_api_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
