// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace api {

static const char* Query_method_names[] = {
  "/api.Query/GetSensorRows",
};

std::unique_ptr< Query::Stub> Query::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Query::Stub> stub(new Query::Stub(channel, options));
  return stub;
}

Query::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetSensorRows_(Query_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::api::SensorRows>* Query::Stub::GetSensorRowsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::api::SensorRows>::Create(channel_.get(), rpcmethod_GetSensorRows_, context, request);
}

void Query::Stub::async::GetSensorRows(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::api::SensorRows>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::api::SensorRows>::Create(stub_->channel_.get(), stub_->rpcmethod_GetSensorRows_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::api::SensorRows>* Query::Stub::AsyncGetSensorRowsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::api::SensorRows>::Create(channel_.get(), cq, rpcmethod_GetSensorRows_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::api::SensorRows>* Query::Stub::PrepareAsyncGetSensorRowsRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::api::SensorRows>::Create(channel_.get(), cq, rpcmethod_GetSensorRows_, context, request, false, nullptr);
}

Query::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Query_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Query::Service, ::google::protobuf::Empty, ::api::SensorRows>(
          [](Query::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::api::SensorRows>* writer) {
               return service->GetSensorRows(ctx, req, writer);
             }, this)));
}

Query::Service::~Service() {
}

::grpc::Status Query::Service::GetSensorRows(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::api::SensorRows>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api

