// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: msg.proto
// Protobuf C++ Version: 5.27.0

#include "msg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace msg {

inline constexpr Sensor::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        temp_{0},
        rh_{0},
        epoch_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Sensor::Sensor(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SensorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SensorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SensorDefaultTypeInternal() {}
  union {
    Sensor _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SensorDefaultTypeInternal _Sensor_default_instance_;

inline constexpr LWT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LWT::LWT(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct LWTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LWTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LWTDefaultTypeInternal() {}
  union {
    LWT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LWTDefaultTypeInternal _LWT_default_instance_;
}  // namespace msg
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_msg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_msg_2eproto = nullptr;
const ::uint32_t
    TableStruct_msg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::msg::LWT, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::msg::LWT, _impl_.device_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::msg::Sensor, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::msg::Sensor, _impl_.device_),
        PROTOBUF_FIELD_OFFSET(::msg::Sensor, _impl_.temp_),
        PROTOBUF_FIELD_OFFSET(::msg::Sensor, _impl_.rh_),
        PROTOBUF_FIELD_OFFSET(::msg::Sensor, _impl_.epoch_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::msg::LWT)},
        {9, -1, -1, sizeof(::msg::Sensor)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::msg::_LWT_default_instance_._instance,
    &::msg::_Sensor_default_instance_._instance,
};
const char descriptor_table_protodef_msg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tmsg.proto\022\003msg\"\025\n\003LWT\022\016\n\006device\030\001 \001(\t\""
    "A\n\006Sensor\022\016\n\006device\030\001 \001(\t\022\014\n\004temp\030\002 \001(\005\022"
    "\n\n\002rh\030\003 \001(\002\022\r\n\005epoch\030\004 \001(\003b\006proto3"
};
static ::absl::once_flag descriptor_table_msg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_msg_2eproto = {
    false,
    false,
    114,
    descriptor_table_protodef_msg_2eproto,
    "msg.proto",
    &descriptor_table_msg_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_msg_2eproto::offsets,
    file_level_enum_descriptors_msg_2eproto,
    file_level_service_descriptors_msg_2eproto,
};
namespace msg {
// ===================================================================

class LWT::_Internal {
 public:
};

LWT::LWT(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.LWT)
}
inline PROTOBUF_NDEBUG_INLINE LWT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::msg::LWT& from_msg)
      : device_(arena, from.device_),
        _cached_size_{0} {}

LWT::LWT(
    ::google::protobuf::Arena* arena,
    const LWT& from)
    : ::google::protobuf::Message(arena) {
  LWT* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:msg.LWT)
}
inline PROTOBUF_NDEBUG_INLINE LWT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_(arena),
        _cached_size_{0} {}

inline void LWT::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LWT::~LWT() {
  // @@protoc_insertion_point(destructor:msg.LWT)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void LWT::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.device_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
LWT::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(LWT, _impl_._cached_size_),
              false,
          },
          &LWT::MergeImpl,
          &LWT::kDescriptorMethods,
          &descriptor_table_msg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 22, 2> LWT::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_LWT_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::msg::LWT>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string device = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LWT, _impl_.device_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string device = 1;
    {PROTOBUF_FIELD_OFFSET(LWT, _impl_.device_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\6\0\0\0\0\0\0"
    "msg.LWT"
    "device"
  }},
};

PROTOBUF_NOINLINE void LWT::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.LWT)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* LWT::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.LWT)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string device = 1;
  if (!this->_internal_device().empty()) {
    const std::string& _s = this->_internal_device();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "msg.LWT.device");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.LWT)
  return target;
}

::size_t LWT::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.LWT)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string device = 1;
  if (!this->_internal_device().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_device());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void LWT::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LWT*>(&to_msg);
  auto& from = static_cast<const LWT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.LWT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device().empty()) {
    _this->_internal_set_device(from._internal_device());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LWT::CopyFrom(const LWT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.LWT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LWT::InternalSwap(LWT* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_, &other->_impl_.device_, arena);
}

::google::protobuf::Metadata LWT::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Sensor::_Internal {
 public:
};

Sensor::Sensor(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.Sensor)
}
inline PROTOBUF_NDEBUG_INLINE Sensor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::msg::Sensor& from_msg)
      : device_(arena, from.device_),
        _cached_size_{0} {}

Sensor::Sensor(
    ::google::protobuf::Arena* arena,
    const Sensor& from)
    : ::google::protobuf::Message(arena) {
  Sensor* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, temp_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, temp_),
           offsetof(Impl_, epoch_) -
               offsetof(Impl_, temp_) +
               sizeof(Impl_::epoch_));

  // @@protoc_insertion_point(copy_constructor:msg.Sensor)
}
inline PROTOBUF_NDEBUG_INLINE Sensor::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_(arena),
        _cached_size_{0} {}

inline void Sensor::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, temp_),
           0,
           offsetof(Impl_, epoch_) -
               offsetof(Impl_, temp_) +
               sizeof(Impl_::epoch_));
}
Sensor::~Sensor() {
  // @@protoc_insertion_point(destructor:msg.Sensor)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Sensor::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.device_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Sensor::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Sensor, _impl_._cached_size_),
              false,
          },
          &Sensor::MergeImpl,
          &Sensor::kDescriptorMethods,
          &descriptor_table_msg_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 25, 2> Sensor::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Sensor_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::msg::Sensor>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 epoch = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Sensor, _impl_.epoch_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Sensor, _impl_.epoch_)}},
    // string device = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Sensor, _impl_.device_)}},
    // int32 temp = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Sensor, _impl_.temp_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Sensor, _impl_.temp_)}},
    // float rh = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Sensor, _impl_.rh_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string device = 1;
    {PROTOBUF_FIELD_OFFSET(Sensor, _impl_.device_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 temp = 2;
    {PROTOBUF_FIELD_OFFSET(Sensor, _impl_.temp_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float rh = 3;
    {PROTOBUF_FIELD_OFFSET(Sensor, _impl_.rh_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // int64 epoch = 4;
    {PROTOBUF_FIELD_OFFSET(Sensor, _impl_.epoch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\12\6\0\0\0\0\0\0"
    "msg.Sensor"
    "device"
  }},
};

PROTOBUF_NOINLINE void Sensor::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.Sensor)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_.ClearToEmpty();
  ::memset(&_impl_.temp_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.epoch_) -
      reinterpret_cast<char*>(&_impl_.temp_)) + sizeof(_impl_.epoch_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Sensor::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.Sensor)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string device = 1;
  if (!this->_internal_device().empty()) {
    const std::string& _s = this->_internal_device();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "msg.Sensor.device");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 temp = 2;
  if (this->_internal_temp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_temp(), target);
  }

  // float rh = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = this->_internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        3, this->_internal_rh(), target);
  }

  // int64 epoch = 4;
  if (this->_internal_epoch() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<4>(
            stream, this->_internal_epoch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.Sensor)
  return target;
}

::size_t Sensor::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.Sensor)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string device = 1;
  if (!this->_internal_device().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_device());
  }

  // int32 temp = 2;
  if (this->_internal_temp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_temp());
  }

  // float rh = 3;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = this->_internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    total_size += 5;
  }

  // int64 epoch = 4;
  if (this->_internal_epoch() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_epoch());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Sensor::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Sensor*>(&to_msg);
  auto& from = static_cast<const Sensor&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:msg.Sensor)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device().empty()) {
    _this->_internal_set_device(from._internal_device());
  }
  if (from._internal_temp() != 0) {
    _this->_impl_.temp_ = from._impl_.temp_;
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_rh = from._internal_rh();
  ::uint32_t raw_rh;
  memcpy(&raw_rh, &tmp_rh, sizeof(tmp_rh));
  if (raw_rh != 0) {
    _this->_impl_.rh_ = from._impl_.rh_;
  }
  if (from._internal_epoch() != 0) {
    _this->_impl_.epoch_ = from._impl_.epoch_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Sensor::CopyFrom(const Sensor& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.Sensor)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Sensor::InternalSwap(Sensor* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_, &other->_impl_.device_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensor, _impl_.epoch_)
      + sizeof(Sensor::_impl_.epoch_)
      - PROTOBUF_FIELD_OFFSET(Sensor, _impl_.temp_)>(
          reinterpret_cast<char*>(&_impl_.temp_),
          reinterpret_cast<char*>(&other->_impl_.temp_));
}

::google::protobuf::Metadata Sensor::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_msg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
